Repository rtsoft-gmbh/up2date-win, pull requests merged in 2022-08, with the labels that each got.

#3 #2 Fixed encoding for Bugs_and_issues.txt
  Up2dateService/Bugs_and_issues.txt
Labels: enhancement

#9 4 add ci pipeline
  .github/README.txt
  .github/workflows/build.yaml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .gitignore
  README.md
Labels: enhancement, WIP

#16 RITMS-11: Localization
  .github/workflows/build.yaml
  Up2dateService/Bugs_and_issues.txt
  Up2dateService/Localization.md
  Up2dateService/Setup32/Setup.vdproj
  Up2dateService/Setup64/Setup.vdproj
  Up2dateService/Up2dateClient/Properties/AssemblyInfo.cs
  Up2dateService/Up2dateConsole/App.xaml
  Up2dateService/Up2dateConsole/App.xaml.cs
  Up2dateService/Up2dateConsole/Dialogs/RequestCertificateDialog.xaml
  Up2dateService/Up2dateConsole/Dialogs/RequestCertificateDialogViewModel.cs
  Up2dateService/Up2dateConsole/Fonts/fontawesome-webfont.ttf
  Up2dateService/Up2dateConsole/Helpers/EnumToVisibilityConverter.cs
  Up2dateService/Up2dateConsole/Localization/CheckAndGenerate.cmd
  Up2dateService/Up2dateConsole/Localization/Up2dateConsole_ru-RU.csv
  Up2dateService/Up2dateConsole/MainWindow.xaml
  Up2dateService/Up2dateConsole/MainWindowViewModel.cs
  Up2dateService/Up2dateConsole/PackageItem.cs
  Up2dateService/Up2dateConsole/Properties/AssemblyInfo.cs
  Up2dateService/Up2dateConsole/Properties/Resources.ru-RU.Designer.cs
  Up2dateService/Up2dateConsole/Properties/Resources.ru-RU.resx
  Up2dateService/Up2dateConsole/StateIndicator/ServiceState.cs
  Up2dateService/Up2dateConsole/StateIndicator/StateIndicator.xaml
  Up2dateService/Up2dateConsole/StateIndicator/StateIndicator.xaml.cs
  Up2dateService/Up2dateConsole/StateIndicator/StateIndicatorViewModel.cs
  Up2dateService/Up2dateConsole/StateIndicatorViewModel.cs
  Up2dateService/Up2dateConsole/Styles.xaml
  Up2dateService/Up2dateConsole/Up2dateConsole.csproj
  Up2dateService/Up2dateConsole/ViewService/DialogViewModelBase.cs
  Up2dateService/Up2dateConsole/ViewService/IDialogViewModel.cs
  Up2dateService/Up2dateConsole/ViewService/IViewService.cs
  Up2dateService/Up2dateConsole/ViewService/ViewService.cs
  Up2dateService/Up2dateService.sln
  Up2dateService/Up2dateService/ProjectInstaller.Designer.cs
  Up2dateService/Up2dateService/Properties/AssemblyInfo.cs
  Up2dateService/Up2dateShared/Properties/AssemblyInfo.cs
Labels: documentation, enhancement

#26 Increased Test Results info
  .github/workflows/test.yaml
Labels: enhancement

#41 Update ci.yaml
  .github/workflows/ci.yaml
  .github/workflows/test.yaml
Labels: enhancement
